development:
  adapter: postgresql
  encoding: unicode
  database: new_octoshell_development
  username: octo
  password: octopass

test:
  adapter: postgresql
  encoding: unicode
  database: new_octoshell_test
  username: octo
  password: octopass

production:
  adapter: postgresql
  encoding: unicode
  database: new_octoshell
  username: octo
  password: octopass
  pool: 10
  min_messages: warning
